start = "Добро пожаловать в демонстрацию QIWI Квест!"
questNotFound = "Такого квеста не существует. Нажмите /start чтобы получить доступный список квестов."

questEnding = "Спасибо за прохождение квеста, вы можете пройти его ещё раз или выбрать другой:"
