name = "Тест цикла"
description = "This is a sample"
available = true
startStageName = "stage1"

[[stages]]
name = "stage1"
text = "Первый стейдж"
photoPath = "quest/photo/hackathon_logo.png"

[[stages]]
name = "stage2"
text = "Второй стейдж"

[[stages]]
name = "stage3"
text = "Третий стейдж"

[[stages]]
name = "final"
text = "Конец"

[[nextStages]]
name = "stage2"
value = "На второй стейдж"
answerType = "NO_INLINE_BUTTON"

[[nextStages.nextStages]]
name = "stage3"
value = "На третий стейдж"
answerType = "NO_INLINE_BUTTON"

[[nextStages.nextStages.nextStages]]
name = "final"
value = "На последний стейдж"
answerType = "NO_INLINE_BUTTON"

[[nextStages.nextStages.nextStages]]
name = "stage2"
value = "На второй стейдж"
answerType = "NO_INLINE_BUTTON"

[[nextStages.nextStages]]
name = "stage1"
value = "На первый стейдж"
answerType = "NO_INLINE_BUTTON"
