name = "Quest Example 2"
description = "This is a sample "
available = true
startStageName = "stages1"

[[stages]]
name = "stages1"
text = "Вас приветствует демонстрационный опросник, выберите один из двух вариантов"

[[stages]]
name = "stages2"
text = "Вы выбрали первый вариант. Молодцы, а теперь оставьте своё мнение о данном проекте:"

[[stages]]
name = "stages3"
text = "Вы выбрали второй вариант, неплохо. Оцените ваш опыт от 1 до 10"

[[stages]]
name = "final"
text = "Вот и всё, ребята:)"

[[nextStages]]
name = "stages2"
value = "Вариант 1"
answerType = "NO_INLINE_BUTTON"

[[nextStages.nextStages]]
name = "final"
answerType = "USER_INPUT"
value = ".*"

[[nextStages]]
name = "stages3"
value = "Вариант 2"
answerType = "NO_INLINE_BUTTON"

[[nextStages.nextStages]]
name = "final"
answerType = "USER_INPUT"
value = "^(?:[1-9]|10)$"



