name = "Quest Example"
description = "This is a sample "
available = true

[[stages]]
name = "stages1"
text = "Хуемое"

[[stages]]
name = "stages2"
text = "Хуемое"

[[stages]]
name = "stages3"
text = "Хуемое"

[[stages]]
name = "final"
text = "Хуемое"

[startStage]
name = "stages1"

[[startStage.nextStages]]
name = "stages2"
value = "Вариант 1"
answerType = "NO_INLINE_BUTTON"

[[startstages.nextStages.nextStages]]
name = "final"
answerType = "USER_INPUT"
value = ".*"

[[startstages.nextStages]]
name = "stages3"
value = "Вариант 2"
answerType = "NO_INLINE_BUTTON"

[[startstages.nextStages.nextStages]]
name = "final"
answerType = "USER_INPUT"
value = "^(?:[1-9]|10)$"



